"""empty message

Revision ID: 0d3016282673
Revises: 5a3e0556050b
Create Date: 2022-09-18 03:47:25.674137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3016282673'
down_revision = '5a3e0556050b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gender', type_='foreignkey')
    op.drop_column('gender', 'user_id')
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'user_id')
    op.add_column('user', sa.Column('gender', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('last_location', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'location', ['last_location'], ['id'])
    op.create_foreign_key(None, 'user', 'gender', ['gender'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'last_location')
    op.drop_column('user', 'gender')
    op.add_column('location', sa.Column('user_id', sa.VARCHAR(length=100), nullable=True))
    op.create_foreign_key(None, 'location', 'user', ['user_id'], ['id'])
    op.add_column('gender', sa.Column('user_id', sa.VARCHAR(length=100), nullable=True))
    op.create_foreign_key(None, 'gender', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
