"""empty message

Revision ID: 18260dffd3c3
Revises: 40cef2c992f4
Create Date: 2022-09-16 05:10:57.286357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18260dffd3c3'
down_revision = '40cef2c992f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    # ### end Alembic commands ###
