"""empty message

Revision ID: 1c152ad587f5
Revises: 8505af46ca1e
Create Date: 2022-10-20 15:12:32.901147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c152ad587f5'
down_revision = '8505af46ca1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_image', sa.Column('uploaded_date', sa.DateTime(), nullable=False))
    op.drop_column('profile_image', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_image', sa.Column('date', sa.DATETIME(), nullable=False))
    op.drop_column('profile_image', 'uploaded_date')
    # ### end Alembic commands ###
