"""empty message

Revision ID: 3bbaf0fd21c6
Revises: 18260dffd3c3
Create Date: 2022-09-16 05:14:12.412477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbaf0fd21c6'
down_revision = '18260dffd3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('geolocation_permission', sa.Boolean(), nullable=True))
    op.drop_column('user', 'geolocation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('geolocation', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'geolocation_permission')
    # ### end Alembic commands ###
