"""empty message

Revision ID: 40cef2c992f4
Revises: c206deef6fc8
Create Date: 2022-09-09 01:34:55.605542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40cef2c992f4'
down_revision = 'c206deef6fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_me_gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_me_gender',
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('gender_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['gender_id'], ['gender.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
