"""empty message

Revision ID: 8505af46ca1e
Revises: d9f33d280d70
Create Date: 2022-09-30 06:10:51.148445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8505af46ca1e'
down_revision = 'd9f33d280d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_like',
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('like_id', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['like_id'], ['likes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
