"""empty message

Revision ID: c51f70130d80
Revises: 0d3016282673
Create Date: 2022-09-19 21:27:10.821917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51f70130d80'
down_revision = '0d3016282673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sexual_orientation')
    op.drop_table('user_sexual_orientation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sexual_orientation',
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sexual_orientation_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sexual_orientation_id'], ['sexual_orientation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('sexual_orientation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
