"""empty message

Revision ID: d9f33d280d70
Revises: c51f70130d80
Create Date: 2022-09-23 05:11:52.244721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f33d280d70'
down_revision = 'c51f70130d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'user_id')
    op.add_column('user', sa.Column('last_location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'location', ['last_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'last_location_id')
    op.add_column('location', sa.Column('user_id', sa.VARCHAR(length=100), nullable=True))
    op.create_foreign_key(None, 'location', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
